name: build

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up environment
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential gcc gnu-efi mtools parted ovmf qemu-system-x86

    - name: Build UEFI application
      id: system-paths
      run: |
        export INCLUDE_DIRS="$(dirname $(find /usr/include -name efi.h | head -n 1))"
        export LD_OBJ="$(find /usr/lib -name crt0-efi-x86_64.o | head -n 1)"
        export EFI_LDS="$(find /usr/lib -name elf_x86_64_efi.lds | head -n 1)"
        export BIOS_FD="$(find /usr/share -name OVMF.fd | head -n 1)"
        export LD_EXTRA="-L$(dirname $(find /usr/lib -name libgnuefi.a | head -n 1))"
        make main.efi reboot.img
          
    - name: Archive build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: reboot-artifacts
        path: |
          main.efi
          reboot.img

  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Download build artifacts
      uses: actions/download-artifact@v2
      with:
        name: reboot-artifacts
        path: ./artifacts

    - name: Create a Release
      uses: elgohr/Github-Release-Action@v5
      with:
        body_path: CHANGELOG.md
        files: |
          Release.txt
          LICENSE
        prerelease: false
        draft: false
        fail_on_unmatched_files: true
        generate_release_notes: true
        make_latest: true
      permissions:
        contents: write
