name: release

on:
  tags:
    - '*.*.*'

release:
  needs: build
  runs-on: ubuntu-latest
  if: startsWith(github.ref, 'refs/tags/')
  steps:
  - name: Checkout code
    uses: actions/checkout@v2

  - name: Download build artifacts
    uses: actions/download-artifact@v2
    with:
      name: reboot-artifacts
      path: ./artifacts

  - name: Create a Release
    uses: elgohr/Github-Release-Action@v5
    with:
      body_path: CHANGELOG.md
      files: |
        Release.txt
        LICENSE
      prerelease: false
      draft: false
      fail_on_unmatched_files: true
      generate_release_notes: true
      make_latest: true
    permissions:
      contents: write
